# Generated by Django 4.1.2 on 2022-11-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_course_info_alter_student_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='info',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='about',
            field=models.TextField(max_length=1024),
        ),
    ]
